import { Router } from "express";
import { PrismaClient } from "@prisma/client";
import crypto from "crypto";
import { getRole } from "../utils/economy";

const router = Router();
const prisma = new PrismaClient();

// Function to generate a random 8-character invite code
function generateInviteCode(): string {
  return crypto.randomBytes(4).toString("hex").toUpperCase();
}

// GET /api/invites - Get all invites generated by the current user
router.get("/", async (req: any, res) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader) return res.status(401).json({ success: false, message: "Unauthorized" });
    const userId = authHeader.replace("Bearer ", "").trim();

    const invites = await prisma.inviteCode.findMany({
      where: { createdBy: userId },
      orderBy: { createdAt: "desc" },
    });
    res.json({ success: true, data: invites });
  } catch (error) {
    console.error("Error fetching invites:", error);
    res.status(500).json({ success: false, message: "Internal server error" });
  }
});

// POST /api/invites - Generate a new invite code
router.post("/", async (req: any, res) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader) return res.status(401).json({ success: false, message: "Unauthorized" });
    const userId = authHeader.replace("Bearer ", "").trim();

    const user = await prisma.user.findUnique({ where: { id: userId } });
    if (!user) {
      return res.status(404).json({ success: false, message: "User not found" });
    }

    // Staff (Lead Dev + Admins) can generate unlimited invite keys.
    const role = (user as any).role;
    const isStaff = role === "LEAD_DEV" || role === "ADMIN" || getRole(user.username) !== "USER";

    // Regular users get one free invite; they can buy more with Arise Points.
    if (!isStaff) {
      const existingInvites = await prisma.inviteCode.count({
        where: { createdBy: user.id },
      });

      if (existingInvites >= 1) {
        return res.status(403).json({
          success: false,
          message: "You can only generate one invite key. Buy more with Arise Points.",
        });
      }
    }

    // Generate unique code
    let newCode = generateInviteCode();
    let isUnique = false;
    while (!isUnique) {
      const existing = await prisma.inviteCode.findUnique({ where: { code: newCode } });
      if (!existing) {
        isUnique = true;
      } else {
        newCode = generateInviteCode();
      }
    }

    const invite = await prisma.inviteCode.create({
      data: {
        code: newCode,
        createdBy: user.id,
      },
    });

    res.json({ success: true, data: invite });
  } catch (error) {
    console.error("Error generating invite:", error);
    res.status(500).json({ success: false, message: "Internal server error" });
  }
});

// POST /api/invites/purchase - Buy an EXTRA invite code with Arise Points.
// (Everyone gets one free invite from POST "/"; this lets engaged users buy more.)
const INVITE_COST = 1000;
router.post("/purchase", async (req: any, res) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader) return res.status(401).json({ success: false, message: "Unauthorized" });
    const userId = authHeader.replace("Bearer ", "").trim();

    const user = await prisma.user.findUnique({ where: { id: userId } });
    if (!user) return res.status(404).json({ success: false, message: "User not found" });

    const role = (user as any).role;
    const isStaff = role === "LEAD_DEV" || role === "ADMIN" || getRole(user.username) !== "USER";
    const cost = isStaff ? 0 : INVITE_COST;

    if (cost > 0 && user.arisePoints < cost) {
      return res.status(402).json({
        success: false,
        message: `You need ${INVITE_COST} Arise Points to buy an invite — you have ${user.arisePoints}.`,
      });
    }

    // Generate a unique code.
    let newCode = generateInviteCode();
    while (await prisma.inviteCode.findUnique({ where: { code: newCode } })) {
      newCode = generateInviteCode();
    }

    const invite = await prisma.inviteCode.create({ data: { code: newCode, createdBy: user.id } });

    let arisePoints = user.arisePoints;
    if (cost > 0) {
      const updated = await prisma.user.update({
        where: { id: user.id },
        data: { arisePoints: { decrement: cost } },
      });
      arisePoints = updated.arisePoints;
      await prisma.pointLog.create({ data: { userId: user.id, amount: -cost, reason: "Bought an invite code" } });
    }

    res.json({ success: true, data: invite, cost, arisePoints });
  } catch (error) {
    console.error("Error purchasing invite:", error);
    res.status(500).json({ success: false, message: "Internal server error" });
  }
});

export default router;
